# Generated by Django 4.0.1 on 2022-01-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_description', models.TextField()),
                ('cat_status', models.CharField(default='1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prd_id', models.AutoField(primary_key=True, serialize=False)),
                ('prd_name', models.CharField(default='', max_length=255)),
                ('prd_description', models.TextField(default='')),
                ('prd_price', models.FloatField(default=0)),
                ('prd_strike_price', models.FloatField(default=0)),
                ('prd_currency', models.CharField(default='', max_length=100)),
                ('prd_status', models.CharField(default='1', max_length=10)),
                ('prd_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('prd_created_on', models.DateField(auto_now_add=True)),
                ('prd_parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('meta', models.CharField(default='1', max_length=255)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.products')),
            ],
        ),
    ]
