# Generated by Django 4.0.1 on 2022-02-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='prd_parent_category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='prd_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='prd_strike_price',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
